/* DO NOT CHANGE
 * Autogenerated with Sanity Composer via package script "dev"
 */

import home from "../builder/home";
import page from "../builder/page";

export default [home.getSchema(), page.getSchema()];
