/* DO NOT CHANGE
 * Autogenerated with Sanity Composer via package script "dev"
 */

import localeString from "../builder/objects/locale-string";
import localeText from "../builder/objects/locale-text";
import superSlug from "../builder/objects/super-slug";

export default [
  localeString.getSchema(),
  localeText.getSchema(),
  superSlug.getSchema(),
];
