/* DO NOT CHANGE
 * Autogenerated with Sanity Composer via package script "dev"
 */

import home from "../composables/documents/home";
import page from "../composables/documents/page";
import product from "../composables/documents/product";

export default [home.getSchema(), page.getSchema(), product.getSchema()];
