/* DO NOT CHANGE
 * Autogenerated with Sanity Composer via package script "dev"
 */

import localeString from "../composables/objects/locale-string-object";

export default [localeString.getSchema()];
