/* DO NOT CHANGE
 *
 * Autogenerated with Sanity Composter via package script "dev"
 * on Sunday, August 27, 2023 at 3:13:57 PM
 */

export default /* groq */`
*[_type == "page"] {
  mainSection {
    pageTitle,
    gallery[] {
      caption,
      _key,
      media {
        type,
        type == "image" => {
          "image": image.asset-> {
            url,
            "lqip": metadata.lqip,
            "ratio": metadata.dimensions.aspectRatio
          },
          hotspot,
          crop
        },
        type == "video" => {
          "player": player.asset-> {
            "playbackId": playbackId,
            "ratio": data.aspect_ratio,
            thumbTime
          },
          "mood": mood.asset-> {
            "playbackId": playbackId,
            "ratio": data.aspect_ratio
          }
        }
      }
    }
  },
  callToActions {
    url,
    title
  }
}
`