/* DO NOT CHANGE
 * Autogenerated with Sanity Composer via package script "dev"
 */

export default /* groq */`
*[_type == "page"] {
  mainSection {
    pageTitle,
    gallery[] {
      caption,
      _key,
      media {
        type == "image" => {
          "image": image.asset-> {
            url,
            "lqip": metadata.lqip,
            "ratio": metadata.dimensions.aspectRatio
          },
          hotspot,
          crop
        },
        type == "video" => {
          "player": player.asset-> {
            "playbackId": playbackId,
            "ratio": data.aspect_ratio,
            thumbTime
          },
          "mood": mood.asset-> {
            "playbackId": playbackId,
            "ratio": data.aspect_ratio
          }
        }
      },
      callToActions[] {
        url,
        title
      }
    }
  },
  "seoTitle": coalesce(seoTitle[$lang], seoTitle.en),
  "seoDescription": coalesce(seoDescription[$lang], seoDescription.en),
  seoKeywords,
  callToActions[] {
    url,
    title
  }
}
`