/* DO NOT CHANGE
 * Autogenerated with Sanity Composer via package script "dev"
 */

export default /* groq */ `
*[_type == "home"] {
  "pageTitle": coalesce(pageTitle[$lang], pageTitle.en),
  "seoTitle": coalesce(seoTitle[$lang], seoTitle.en),
  "seoDescription": coalesce(seoDescription[$lang], seoDescription.en),
  seoKeywords,
  gallery[] {
    caption,
    _key
  },
  ...
}
`;
