
  /* Autogenerated. Don't touch! */

  export const pageSchema = {
  type: "document",
  name: "page",
  fields: [
    {
      type: "object",
      name: "mainSections",
      fields: [
        { name: "pageTitle", type: "string" },
        {
          type: "array",
          name: "gallery",
          of: [
            {
              name: "media",
              type: "object",
              fields: [
                {
                  name: "type",
                  title: "Type",
                  type: "string",
                  options: {
                    list: ["image", "video"],
                    layout: "radio",
                    direction: "horizontal",
                  },
                  hidden: true,
                  initialValue: "image",
                },
                {
                  name: "mood",
                  title: "Mood Video",
                  description:
                    "Automatic playback without audio. Videos should be max. 10 seconds long.",
                  type: "file",
                },
                {
                  name: "player",
                  title: "Video Player",
                  description:
                    "Video Player with all playback controls. If combined with a mood video, the mood video will replace the image poster.",
                  type: "file",
                },
                { name: "image", type: "image", options: { hotspot: true } },
              ],
              preview: {
                select: {
                  type: "type",
                  mood: "mood.asset.playbackId",
                  player: "player.asset.playbackId",
                  image: "image",
                },
              },
            },
          ],
        },
      ],
    },
    {
      type: "array",
      name: "callToAction",
      of: [
        {
          name: "link",
          type: "object",
          fields: [
            { name: "title", type: "string" },
            { name: "url", type: "url" },
          ],
        },
      ],
    },
  ],
};
